import { chromium } from "playwright";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto("http://localhost:3001/", { waitUntil: "networkidle" });
await page.waitForTimeout(2600);
await page.evaluate(() => document.querySelector("#about")?.scrollIntoView());
await page.waitForTimeout(1800);
await page.screenshot({ path: "scripts/about.png" });
await page.evaluate(() => document.querySelector("#contact")?.scrollIntoView());
await page.waitForTimeout(1500);
await page.screenshot({ path: "scripts/contact.png" });
await browser.close();
console.log("done");
